name: Docker CI/CD

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the workflow on an Ubuntu runner
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/first_docker_repository:$GITHUB_SHA .
        # Replace 'my-node-app' with the name of your app
    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/first_docker_repository:$GITHUB_SHA
        # Replace 'my-node-app' with your app's name
# Deploy on EC2 via SSH
    - name: SSH Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.EC2_PUBLIC_IP }}      # This is terraform output
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}        # Private key
        script: |
          bash /home/ubuntu/deploy.sh
          git pull
          npm install
          pm2 restart all
